version: '3.1'
services:
  app:
    container_name: docker-springboot-postgresql
    image: docker-springboot-postgresql
    build: ./
    ports:
      - "8890:8890"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fas10ver

networks:
  semNetwork:
    driver: "bridge"

